## Importing numpy library

In [1]:
import numpy as np

## Creating numpy arrays and initializing

In [2]:
## Create one dimensional array
a = np.array([1, 2, 3]) 
a

array([1, 2, 3])

In [3]:
## Find the type of the object
type(a) 

numpy.ndarray

In [4]:
## Find the dimension of the array
a.shape

(3,)

In [5]:
print( a[1] )

2


In [6]:
# Create a two dimensional array
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print( b )

[[1 2 3]
 [4 5 6]]


In [7]:
print( b.shape )

(2, 3)


In [8]:
print( b[0, :] )

[1 2 3]


In [9]:
print( b[:, 1] )

[2 5]


In [10]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
b[:]

array([[1, 2, 3],
       [4, 5, 6]])

## Special Initializing functions

In [12]:
a = np.zeros((2,2))  # Create an array of all zeros
# Prints "[[ 0.  0.]
#          [ 0.  0.]]"
a

array([[ 0.,  0.],
       [ 0.,  0.]])

In [13]:
b = np.ones((1,2)) # Create an array of all ones
#  [[ 1  1]]
b

array([[ 1.,  1.]])

In [14]:
d = np.eye(2) 

In [15]:
d

array([[ 1.,  0.],
       [ 0.,  1.]])

In [16]:
c = np.full((2,2), 7)

In [17]:
c

array([[ 7.,  7.],
       [ 7.,  7.]])

In [18]:
e = np.random.random((2,2) )

In [19]:
e

array([[ 0.30436023,  0.83147814],
       [ 0.28156837,  0.24347409]])

In [20]:
f = np.random.randint(10, size = (4,4) )

In [21]:
f

array([[6, 4, 5, 9],
       [5, 4, 0, 1],
       [9, 6, 3, 7],
       [2, 2, 7, 6]])

## Slicing & Indexing an array

In [22]:
# Get first row
f[0,:]

array([6, 4, 5, 9])

In [23]:
# Get 1 and 2 row
f[0:2,:]

array([[6, 4, 5, 9],
       [5, 4, 0, 1]])

In [24]:
f[:, 1]

array([4, 4, 6, 2])

In [25]:
# Get first column
f[:,0]

array([6, 5, 9, 2])

In [26]:
f[:,0:2]

array([[6, 4],
       [5, 4],
       [9, 6],
       [2, 2]])

In [27]:
## slicing an array 
## All 
b = f[:2, 1:3]

In [28]:
b

array([[4, 5],
       [4, 0]])

In [29]:
## Get specific elements
np.array([f[0,1], f[2,2]])

array([4, 3])

In [30]:
## Boolean indexing
f>2

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [ True,  True,  True,  True],
       [False, False,  True,  True]], dtype=bool)

In [31]:
g = f[f>2]

In [32]:
g

array([6, 4, 5, 9, 5, 4, 9, 6, 3, 7, 7, 6])

## Reshaping an array

In [33]:
np.reshape( f, ( 8,2 ) )

array([[6, 4],
       [5, 9],
       [5, 4],
       [0, 1],
       [9, 6],
       [3, 7],
       [2, 2],
       [7, 6]])

## Numpy Maths

## Adding, substracting, multiplying, tranposing arrays

In [34]:
x = np.random.randint( 100, size = (5,5) )
y = np.random.randint( 100, size = (5,5) )

In [35]:
x

array([[26, 87, 31, 73, 68],
       [26, 48, 80, 29, 27],
       [ 3, 53, 69, 68, 43],
       [68, 58, 41, 63, 60],
       [55, 44, 20, 25, 15]])

In [36]:
y

array([[54, 80, 19, 76, 64],
       [28, 71, 34, 28, 53],
       [ 4, 25, 87, 36, 64],
       [82, 93, 45, 58, 68],
       [ 8, 22,  7, 99, 44]])

In [37]:
## Add two matrices x + y or np.add( x, y )
x + y

array([[ 80, 167,  50, 149, 132],
       [ 54, 119, 114,  57,  80],
       [  7,  78, 156, 104, 107],
       [150, 151,  86, 121, 128],
       [ 63,  66,  27, 124,  59]])

In [38]:
np.add( x, y )

array([[ 80, 167,  50, 149, 132],
       [ 54, 119, 114,  57,  80],
       [  7,  78, 156, 104, 107],
       [150, 151,  86, 121, 128],
       [ 63,  66,  27, 124,  59]])

In [39]:
# np.substract( x, y )
x - y

array([[-28,   7,  12,  -3,   4],
       [ -2, -23,  46,   1, -26],
       [ -1,  28, -18,  32, -21],
       [-14, -35,  -4,   5,  -8],
       [ 47,  22,  13, -74, -29]])

In [40]:
# np.multiply( x, y )
x * y

array([[1404, 6960,  589, 5548, 4352],
       [ 728, 3408, 2720,  812, 1431],
       [  12, 1325, 6003, 2448, 2752],
       [5576, 5394, 1845, 3654, 4080],
       [ 440,  968,  140, 2475,  660]])

In [41]:
# Matrix Transpose
x.T

array([[26, 26,  3, 68, 55],
       [87, 48, 53, 58, 44],
       [31, 80, 69, 41, 20],
       [73, 29, 68, 63, 25],
       [68, 27, 43, 60, 15]])

In [42]:
np.sum( x )

1180

In [43]:
np.sum( x, axis = 0 )

array([178, 290, 241, 258, 213])

In [44]:
np.sum( x, axis = 1 )

array([285, 210, 236, 290, 159])

## Linear Algebra.. Advanced Matrix Operation

In [45]:
from numpy import linalg

## Solving a set of linear equations

- 2x + 2y = 5
- 3x + y = 7

In [46]:
a = np.array([[2,2], [3,1]])
b = np.array([5,7])
x = np.linalg.solve(a, b)
x

array([ 2.25,  0.25])

## Matrix Inversion

In [47]:
a = np.array([[1, 2], [3, 4]])
linalg.inv( a )

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

## Calculating an eigen value and vector for a matrix

In [48]:
m1 = np.diag((1, 2, 3))
m1

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [49]:
eigval, eigvec = linalg.eig( m1 )

In [50]:
eigval

array([ 1.,  2.,  3.])

In [51]:
eigvec

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])